services:
  postgres:
    image: postgres:17
    
    container_name: postgres_data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  default:
    driver: bridge
    name: dev_network

volumes:
  postgres_data: